/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author asus
 */
public class university extends javax.swing.JFrame {

    /**
     * Creates new form university
     */
    public university() {
        initComponents();
        show_uni();
    }

    public ArrayList<uni> uniList() {
        ArrayList<uni> uniList = new ArrayList<>();
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection connection = null;
            connection = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1533/cse1.omega.uta.edu", "vkp2822", "Mavs2018");
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery("select * from F18_6_university");
            uni uni;
            while (rs.next()) {
                uni = new uni(rs.getString("UNIVERSITY_ID"), rs.getString("UNIVERSITY_NAME"), rs.getString("UNIVERSITY_ADDRESS"), rs.getInt("TIER"));
                uniList.add(uni);
            }
        } catch (Exception e) {
            System.out.println("Connection Failed! Check output console");
            e.printStackTrace();

        }
        return uniList;
    }

    public void show_uni() {
        ArrayList<uni> list = uniList();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_university.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getUNIVERSITY_ID();
            row[1] = list.get(i).getUNIVERSITY_NAME();
            row[2] = list.get(i).getUNIVERSITY_ADDRESS();
            row[3] = list.get(i).getTIER();
            model.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_university = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        UNIVERSITY_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        UNIVERSITY_NAME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        UNIVERSITY_ADDRESS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TIER = new javax.swing.JTextField();
        SAVE = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        RESET = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Display_university.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UNIVERSITY_ID", "UNIVERSITY_NAME ", "UNIVERSITY_ADDRESS ", "TIER"
            }
        ));
        jTable_Display_university.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_universityMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_university);

        jLabel1.setText("UNIVERSITY_ID:");

        UNIVERSITY_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNIVERSITY_IDActionPerformed(evt);
            }
        });

        jLabel2.setText("UNIVERSITY_NAME:");

        jLabel3.setText("UNIVERSITY_ADDRESS:");

        jLabel4.setText("TIER");

        TIER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIERActionPerformed(evt);
            }
        });

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(UNIVERSITY_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UNIVERSITY_ADDRESS)
                            .addComponent(UNIVERSITY_ID)
                            .addComponent(TIER))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UNIVERSITY_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UNIVERSITY_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UNIVERSITY_ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TIER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAVE)
                    .addComponent(UPDATE))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DELETE)
                    .addComponent(RESET))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TIERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIERActionPerformed

    private void UNIVERSITY_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNIVERSITY_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UNIVERSITY_IDActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection connection = null;
            connection = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1533/cse1.omega.uta.edu", "vkp2822", "Mavs2018");

            String query = ("insert into f18_6_university(UNIVERSITY_ID,UNIVERSITY_NAME,UNIVERSITY_ADDRESS,TIER) values(?,?,?,?)");
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, UNIVERSITY_ID.getText());
            pst.setString(2, UNIVERSITY_NAME.getText());
            pst.setString(3, UNIVERSITY_ADDRESS.getText());
            pst.setString(4, TIER.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) jTable_Display_university.getModel();
            model.setRowCount(0);
            show_uni();
            JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");

        } 
        catch (Exception e) {
            System.out.println("Connection Failed! Check output console");
            e.printStackTrace();

        }
    }//GEN-LAST:event_SAVEActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        UNIVERSITY_ID.setText("");
        UNIVERSITY_NAME.setText("");
        UNIVERSITY_ADDRESS.setText("");
        TIER.setText("");
    }//GEN-LAST:event_RESETActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
         try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection connection = null;
            connection = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1533/cse1.omega.uta.edu", "vkp2822", "Mavs2018");
            int row = jTable_Display_university.getSelectedRow();
            String value = (jTable_Display_university.getModel().getValueAt(row,0).toString());
            String query = "UPDATE F18_6_UNIVERSITY SET UNIVERSITY_ID=?, UNIVERSITY_NAME=?, UNIVERSITY_ADDRESS=?, TIER=? WHERE UNIVERSITY_ID="+value;
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, UNIVERSITY_ID.getText());
            pst.setString(2, UNIVERSITY_NAME.getText());
            pst.setString(3, UNIVERSITY_ADDRESS.getText());
            pst.setString(4, TIER.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) jTable_Display_university.getModel();
            model.setRowCount(0);
            show_uni();
            JOptionPane.showMessageDialog(null, "Updaated Sucessfully!");
            
         }
         catch (Exception e) {
            System.out.println("Connection Failed! Check output console");
            e.printStackTrace();

        }
         
    }//GEN-LAST:event_UPDATEActionPerformed

    private void jTable_Display_universityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_universityMouseClicked
        int i = jTable_Display_university.getSelectedRow();
        TableModel model= jTable_Display_university.getModel();
        UNIVERSITY_ID.setText(model.getValueAt(i,0).toString());
        UNIVERSITY_NAME.setText(model.getValueAt(i,1).toString());
        UNIVERSITY_ADDRESS.setText(model.getValueAt(i,2).toString());
        TIER.setText(model.getValueAt(i,3).toString());
        
    }//GEN-LAST:event_jTable_Display_universityMouseClicked

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection connection = null;
            connection = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1533/cse1.omega.uta.edu", "vkp2822", "Mavs2018");
            int row = jTable_Display_university.getSelectedRow();
            String value = (jTable_Display_university.getModel().getValueAt(row,0).toString());
            String query = "DELETE FROM F18_6_UNIVERSITY where UNIVERSITY_ID="+value;
            PreparedStatement pst = connection.prepareStatement(query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) jTable_Display_university.getModel();
            model.setRowCount(0);
            show_uni();
            JOptionPane.showMessageDialog(null, "Deleted Sucessfully!");
        }
        catch (Exception e) {
            System.out.println("Connection Failed! Check output console");
            e.printStackTrace();

        }
    }//GEN-LAST:event_DELETEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(university.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(university.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(university.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(university.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new university().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETE;
    private javax.swing.JButton RESET;
    private javax.swing.JButton SAVE;
    private javax.swing.JTextField TIER;
    private javax.swing.JTextField UNIVERSITY_ADDRESS;
    private javax.swing.JTextField UNIVERSITY_ID;
    private javax.swing.JTextField UNIVERSITY_NAME;
    private javax.swing.JButton UPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_university;
    // End of variables declaration//GEN-END:variables
}
